DROP DATABASE IF EXISTS employeeDB;

CREATE DATABASE employeeDB;

USE employeeDB;

CREATE TABLE employee (
id INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(30) UNIQUE NOT NULL,
last_name VARCHAR(30),
role_id INT UNSIGNED NOT NULL,
manager_id INT UNSIGNED NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE roles (
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(30) UNIQUE NOT NULL,
salary DECIMAL(10,0) UNSIGNED NOT NULL,
department_id INT UNSIGNED NOT NULL,
PRIMARY KEY (id)
);